"""The event record and the vocabulary of event types."""
from __future__ import annotations

from dataclasses import dataclass
from typing import Any


@dataclass(frozen=True)
class Event:
    event_id: str
    seq: int
    ts: str
    actor_id: str
    type: str
    payload: dict[str, Any]
    causation_id: str | None
    correlation_id: str


# Event type vocabulary. Kept as constants so typos fail at import, not at runtime.
ACTOR_REGISTERED = "ACTOR_REGISTERED"
ASSET_LISTED = "ASSET_LISTED"
ORDER_POSTED = "ORDER_POSTED"
ORDER_EXPIRED = "ORDER_EXPIRED"
ORDER_FILLED = "ORDER_FILLED"
MATCH_PROPOSED = "MATCH_PROPOSED"
POLICY_DECIDED = "POLICY_DECIDED"
SETTLEMENT_INITIATED = "SETTLEMENT_INITIATED"
SETTLEMENT_COMPLETED = "SETTLEMENT_COMPLETED"
SETTLEMENT_FAILED = "SETTLEMENT_FAILED"
CREDITS_TRANSFERRED = "CREDITS_TRANSFERRED"
RECALL_INJECTED = "RECALL_INJECTED"
LESSON_CONSOLIDATED = "LESSON_CONSOLIDATED"
NEGOTIATION_OPENED = "NEGOTIATION_OPENED"
NEGOTIATION_ROUND = "NEGOTIATION_ROUND"
NEGOTIATION_ENDED = "NEGOTIATION_ENDED"
COUNTERPARTY_CHOSEN = "COUNTERPARTY_CHOSEN"
INSIGHT_MINTED = "INSIGHT_MINTED"
PRIVACY_REFUSED = "PRIVACY_REFUSED"
AUCTION_OPENED = "AUCTION_OPENED"
BID_PLACED = "BID_PLACED"
AUCTION_CLEARED = "AUCTION_CLEARED"
RECONCILED = "RECONCILED"
DRIFT_DETECTED = "DRIFT_DETECTED"
INVARIANT_VIOLATED = "INVARIANT_VIOLATED"
POINTS_MINTED = "POINTS_MINTED"
ACTOR_FROZEN = "ACTOR_FROZEN"
ACTOR_RESUMED = "ACTOR_RESUMED"
